### ISSUE TITLE
MPS crashes when server is not built 

### ISSUE THREAD

**Issue by adamarjian1** [o3de/o3de-multiplayersample#135] opened 2022-04-13 19:21 UTC
**Describe the bug**
After installing and building the multiplayer sample, I run the sample level and it crashes when server is not built .

**Steps to reproduce**
1. Open SampleBase
2. Press CTRL+G

**Expected behavior**
I expect it to run the game or if no server is included get an error message

**Actual behavior**
Crashes

**Found in Branch**
Dev

**Desktop/Device (please complete the following information):**
PC Windows

**Comment by adamarjian1** [comment] 2022-04-13 19:22
#8407

**Comment by lmbr-pip** [comment] 2022-04-14 17:52
Need a few more details on branch / installer to aid reproducing

**Comment by AMZN-Gene** [comment] 2022-04-14 17:54
Does not repro in AutomatedTesting. I get error logs....

**Comment by AMZN-Gene** [comment] 2022-04-15 16:44
@adamarjian1 had downloaded the MPS from the GitHub zip file which is corrupt because the zip contains the LFS hash files instead of the real assets and so all the assets were failing. Closing.

**Closed by AMZN-Gene** 2022-04-15 16:44 UTC
Labels: kind/bug, sig/network, needs-triage
