### ISSUE TITLE
SpawnifAuthority.scriptcanvas is failing to process in AP

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de-multiplayersample#120] opened 2022-03-07 14:51 UTC
**Describe the bug**
Development branch:
C:/git/o3de-multiplayersample/scriptcanvas/SpawnIfAuthority.scriptcanvas is failing to process in AP

**Steps to reproduce**
1. Build o3de-multiplayersample in development branch
2. Run AP

**Expected behavior**
All assets are processed.

**Actual behavior**
C:/git/o3de-multiplayersample/scriptcanvas/SpawnIfAuthority.scriptcanvas
fails with:

```
~~1646664112199~~3~~0000000000001B44~~Error~~Failed processing C:/git/o3de-multiplayersample/scriptcanvas/SpawnIfAuthority.scriptcanvas
~~1646664112200~~3~~0000000000001B44~~Error~~CreateJobs of scriptcanvas/SpawnIfAuthority.scriptcanvas has failed.
~~1646664112200~~3~~0000000000001B44~~Error~~This is often because the asset is corrupt.
~~1646664112201~~3~~0000000000001B44~~Error~~Please load it in the editor to see what might be wrong.
~~1646664112202~~1~~0000000000001B44~~AssetBuilder~~AssetBuilder: Source = C:/git/o3de-multiplayersample\scriptcanvas/SpawnIfAuthority.scriptcanvas
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~AssetBuilder: Platforms = pc
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~ScriptCanvasBuilder: Start Creating Job
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System:
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~==================================================================
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: Trace::Assert
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~ D:\Users\mrole\.o3de\3rdParty\packages\RapidJSON-1.1.0-rev1-multiplatform\RapidJSON\include\rapidjson/document.h(1231): (19156) 'class rapidjson_ly::GenericValue<struct rapidjson_ly::UTF8<char>,class rapidjson_ly::MemoryPoolAllocator<class rapidjson_ly::CrtAllocator> > &__cdecl rapidjson_ly::GenericValue<struct rapidjson_ly::UTF8<char>,class rapidjson_ly::MemoryPoolAllocator<class rapidjson_ly::CrtAllocator> >::operator []<class rapidjson_ly::MemoryPoolAllocator<class rapidjson_ly::CrtAllocator>>(const class rapidjson_ly::GenericValue<struct rapidjson_ly::UTF8<char>,class rapidjson_ly::MemoryPoolAllocator<class rapidjson_ly::CrtAllocator> > &)'
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: Assert[rapidjson]: false
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: ==================================================================
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System:
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~==================================================================
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: Trace::Assert
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~ D:\Users\mrole\.o3de\3rdParty\packages\RapidJSON-1.1.0-rev1-multiplatform\RapidJSON\include\rapidjson/document.h(1803): (19156) 'unsigned int __cdecl rapidjson_ly::GenericValue<struct rapidjson_ly::UTF8<char>,class rapidjson_ly::MemoryPoolAllocator<class rapidjson_ly::CrtAllocator> >::GetUint(void) const'
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: Assert[rapidjson]: data_.f.flags & kUintFlag
~~1646664112203~~1~~0000000000001B44~~AssetBuilder~~System: ==================================================================
~~1646664112203~~2~~0000000000001B44~~AssetBuilder~~Serialization: Trace::Warning
~~1646664112203~~2~~0000000000001B44~~AssetBuilder~~>	C:\git\o3de\Code\Framework\AzCore\AzCore\Serialization\SerializationUtils.cpp(66): 'bool __cdecl AZ::Utils::LoadObjectFromStreamInPlace(class AZ::IO::GenericStream &,class AZ::SerializeContext *,const class AZ::SerializeContext::ClassData *,void *,const struct AZ::ObjectStream::FilterDescriptor &)'
~~1646664112203~~2~~0000000000001B44~~AssetBuilder~~>	LoadObjectFromStreamInPlace: Did not find the expected type in the stream
~~1646664112204~~3~~0000000000001B44~~AssetBuilder~~Assert[rapidjson]: false
~~1646664112204~~3~~0000000000001B44~~AssetBuilder~~Assert[rapidjson]: data_.f.flags & kUintFlag
~~1646664112204~~3~~0000000000001B44~~AssetBuilder~~Graph component is missing from entity.
~~1646664112205~~3~~0000000000001B44~~AssetBuilder~~GraphData is missing from entity
~~1646664112205~~3~~0000000000001B44~~AssetBuilder~~Exception : 0xC0000005 - 'EXCEPTION_ACCESS_VIOLATION' [00007FFC1AC61A3D]
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~ScriptCanvasBuilder: Failed to load the file: C:\git\o3de-multiplayersample\scriptcanvas\SpawnIfAuthority.scriptcanvas
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System:
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~==================================================================
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: Trace::Assert
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~ C:\git\o3de\Gems\ScriptCanvas\Code\Builder\ScriptCanvasBuilderWorker.cpp(65): (19156) 'void __cdecl ScriptCanvasBuilder::Worker::CreateJobs(const struct AssetBuilderSDK::CreateJobsRequest &,struct AssetBuilderSDK::CreateJobsResponse &) const'
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: Graph component is missing from entity.
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: ==================================================================
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System:
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~==================================================================
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: Trace::Assert
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~ C:\git\o3de\Gems\ScriptCanvas\Code\Builder\ScriptCanvasBuilderWorker.cpp(66): (19156) 'void __cdecl ScriptCanvasBuilder::Worker::CreateJobs(const struct AssetBuilderSDK::CreateJobsRequest &,struct AssetBuilderSDK::CreateJobsResponse &) const'
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: GraphData is missing from entity
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: ==================================================================
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: ==================================================================
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: Exception : 0xC0000005 - 'EXCEPTION_ACCESS_VIOLATION' [00007FFC1AC61A3D]
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: C:\git\o3de\Gems\ScriptCanvas\Code\Builder\ScriptCanvasBuilderWorker.cpp (77) : ScriptCanvasBuilder::Worker::CreateJobs
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: C:\git\o3de\Code\Tools\AssetProcessor\AssetBuilder\AssetBuilderComponent.cpp (951) : AssetBuilderComponent::JobThread
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: C:\git\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: 00007FFCE0D86C0C (ucrtbase) : recalloc
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: 00007FFCE1A354E0 (KERNEL32) : BaseThreadInitThunk
~~1646664112206~~1~~0000000000001B44~~AssetBuilder~~System: 00007FFCE318485B (ntdll) : RtlUserThreadStart
~~1646664112206~~3~~0000000000001B44~~AssetBuilder~~00007FFCE07B2991 (KERNELBASE) : UnhandledExceptionFilter
~~1646664112206~~3~~0000000000001B44~~AssetBuilder~~00007FFCE322A76C (ntdll) : memset
~~1646664112207~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32137D6 (ntdll) : _C_specific_handler
~~1646664112207~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32286EF (ntdll) : _chkstk
~~1646664112208~~3~~0000000000001B44~~AssetBuilder~~00007FFCE31B5AEA (ntdll) : RtlRestoreContext
~~1646664112208~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32276FE (ntdll) : KiUserExceptionDispatcher
~~1646664112209~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Gems\ScriptCanvas\Code\Builder\ScriptCanvasBuilderWorker.cpp (77) : ScriptCanvasBuilder::Worker::CreateJobs
~~1646664112209~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Tools\AssetProcessor\AssetBuilder\AssetBuilderComponent.cpp (951) : AssetBuilderComponent::JobThread
~~1646664112209~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
~~1646664112210~~3~~0000000000001B44~~AssetBuilder~~00007FFCE0D86C0C (ucrtbase) : recalloc
~~1646664112210~~3~~0000000000001B44~~AssetBuilder~~00007FFCE1A354E0 (KERNEL32) : BaseThreadInitThunk
~~1646664112211~~3~~0000000000001B44~~AssetBuilder~~00007FFCE318485B (ntdll) : RtlUserThreadStart
~~1646664112211~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.cpp (236) : AZ::Debug::Trace::Terminate
~~1646664112212~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Tools\AssetProcessor\AssetBuilder\TraceMessageHook.cpp (137) : AssetBuilder::TraceMessageHook::OnException
~~1646664112212~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1400) : AZ::Internal::EBusContainer<AZ::Debug::TraceMessageEvents,AZ::Debug::TraceMessageEvents,0,1>::Dispatcher<AZ::EBus<AZ::Debug::TraceMessageEvents,AZ::Debug::TraceMessageEvents>
~~1646664112212~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\Debug\Trace_WinAPI.cpp (190) : AZ::Debug::ExceptionHandler
~~1646664112213~~3~~0000000000001B44~~AssetBuilder~~00007FFCE07B2991 (KERNELBASE) : UnhandledExceptionFilter
~~1646664112213~~3~~0000000000001B44~~AssetBuilder~~00007FFCE322A76C (ntdll) : memset
~~1646664112214~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32137D6 (ntdll) : _C_specific_handler
~~1646664112214~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32286EF (ntdll) : _chkstk
~~1646664112214~~3~~0000000000001B44~~AssetBuilder~~00007FFCE31B5AEA (ntdll) : RtlRestoreContext
~~1646664112215~~3~~0000000000001B44~~AssetBuilder~~00007FFCE32276FE (ntdll) : KiUserExceptionDispatcher
~~1646664112215~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Gems\ScriptCanvas\Code\Builder\ScriptCanvasBuilderWorker.cpp (77) : ScriptCanvasBuilder::Worker::CreateJobs
~~1646664112216~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Tools\AssetProcessor\AssetBuilder\AssetBuilderComponent.cpp (951) : AssetBuilderComponent::JobThread
~~1646664112216~~3~~0000000000001B44~~AssetBuilder~~C:\git\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
~~1646664112216~~3~~0000000000001B44~~AssetBuilder~~00007FFCE0D86C0C (ucrtbase) : recalloc
~~1646664112217~~3~~0000000000001B44~~AssetBuilder~~00007FFCE1A354E0 (KERNEL32) : BaseThreadInitThunk
~~1646664112217~~3~~0000000000001B44~~AssetBuilder~~00007FFCE318485B (ntdll) : RtlUserThreadStart
~~1646664112218~~3~~0000000000001B44~~Builder~~Lost connection to asset builder
~~1646664112218~~3~~0000000000001B44~~Builder~~Lost connection to asset builder
~~1646664112219~~3~~0000000000001B44~~Error~~Builder indicated that the job has failed.
```

**Assets required**
o3de-multiplayersample
C:/git/o3de-multiplayersample/scriptcanvas/SpawnIfAuthority.scriptcanvas

**Found in Branch**
development, 3/7/2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5900x
 - GPU NVidia RTX 3090
 - Memory 64GB

**Additional context**

**Comment by AMZN-Gene** [comment] 2022-03-10 18:49
I'll create a bug for this in o3de, link it, and close this one out.

**Comment by AMZN-Gene** [comment] 2022-03-11 23:58
Closing this as duplicate of another issue related to spawning in script. https://github.com/o3de/o3de/issues/8206

**Closed by AMZN-Gene** 2022-03-11 23:58 UTC
Labels: kind/bug, sig/network, needs-triage
